//-| File path: types/cypress.types.ts
export enum DataCyAttributes {
  SUCCESS_AUTH_SIGN_IN = "success-auth-sign-in",
  ERROR_AUTH_SIGN_IN = "error-auth-sign-in",
  SUCCESS_AUTH_SIGN_UP = "success-auth-sign-up",
  ERROR_AUTH_SIGN_UP = "error-auth-sign-up",
  AUTH_DIALOG = "auth-dialog",
  AUTH_EMAIL_INPUT = "auth-email-input",
  AUTH_PASSWORD_INPUT = "auth-password-input",
  AUTH_SUBMIT_BUTTON = "auth-submit-button",
  AUTH_TOGGLE_MODE_BUTTON = "auth-toggle-mode-button",
  AUTH_DELETE_ACCOUNT_BUTTON = "auth-delete-account-button",
  SIGN_IN_BUTTON = "sign-in-button",
  PROFILE_BUTTON = "profile-button",
  SIGN_OUT_BUTTON = "sign-out-button",
  SUCCESS_SIGN_OUT = "success-sign-out",
  ERROR_SIGN_OUT = "error-sign-out",
  SUCCESS_RESEND_EMAIL = "success-resend-email",
  ERROR_RESEND_EMAIL = "error-resend-email",
  SUCCESS_ONBOARDING_SAVE = "success-onboarding-save",
  ERROR_ONBOARDING_SAVE = "error-onboarding-save",
  SUCCESS_VERIFY_ACCOUNT = "success-verify-account",
  ERROR_VERIFY_ACCOUNT = "error-verify-account",
  SUCCESS_DELETE_ACCOUNT = "success-delete-account",
  ERROR_DELETE_ACCOUNT = "error-delete-account",
  TOGGLE_SIDEBAR_BUTTON = "toggle-sidebar-button",
  RESEND_EMAIL_BUTTON = "resend-email-button",
  SIGN_OUT_VERIFY_BUTTON = "sign-out-verify-button",
  VERIFY_ACCOUNT_BUTTON = "verify-account-button",
  ONBOARDING_DIALOG = "onboarding-dialog",
  ONBOARDING_FIRST_NAME_INPUT = "onboarding-first-name-input",
  ONBOARDING_LAST_NAME_INPUT = "onboarding-last-name-input",
  ONBOARDING_COMPANY_INPUT = "onboarding-company-input",
  ONBOARDING_PHONE_INPUT = "onboarding-phone-input",
  ONBOARDING_AVATAR_UPLOAD = "onboarding-avatar-upload",
  ONBOARDING_AVATAR_CHANGE_BUTTON = "onboarding-avatar-change-button",
  ONBOARDING_AVATAR_REMOVE_BUTTON = "onboarding-avatar-remove-button",
  ONBOARDING_AVATAR_BROWSE_BUTTON = "onboarding-avatar-browse-button",
  ONBOARDING_BACK_BUTTON = "onboarding-back-button",
  ONBOARDING_NEXT_BUTTON = "onboarding-next-button",
  ONBOARDING_SAVE_BUTTON = "onboarding-save-button",
  CONVERSATION_ITEM = "conversation-item",
  UNREAD_BADGE = "unread-badge",
  CREATE_CONTRACT_BUTTON = "create-contract-button",
  CONTRACT_ITEM = "contract-item",
  CONTRACT_UNAPPROVED_BADGE = "contract-unapproved-badge",
  CONTRACT_PAID_BADGE = "contract-paid-badge",
  PROFILE_MENU_BUTTON = "profile-menu-button",
  ADMIN_BUTTON = "admin-button",
  PROFILE_BUTTON_COLLAPSED = "profile-button-collapsed",
  SIGN_OUT_BUTTON_COLLAPSED = "sign-out-button-collapsed",
  SIGN_OUT_CONFIRM_DIALOG = "sign-out-confirm-dialog",
  SIGN_OUT_CONFIRM_TITLE = "sign-out-confirm-title",
  SIGN_OUT_CONFIRM_DESCRIPTION = "sign-out-confirm-description",
  SIGN_OUT_CANCEL_BUTTON = "sign-out-cancel-button",
  SIGN_OUT_CONFIRM_BUTTON = "sign-out-confirm-button",
  USER_TABLE_SEARCH_INPUT = "user-table-search-input",
  USER_TABLE_NAME_HEADER = "user-table-name-header",
  USER_TABLE_EMAIL_HEADER = "user-table-email-header",
  USER_TABLE_MESSAGE_HEADER = "user-table-message-header",
  USER_TABLE_CONTRACT_TITLE_HEADER = "user-table-contract-title-header",
  USER_TABLE_STATUS_HEADER = "user-table-status-header",
  USER_TABLE_USER_CREATED_HEADER = "user-table-user-created-header",
  USER_TABLE_CONTRACT_CREATED_HEADER = "user-table-contract-created-header",
  USER_TABLE_ROW = "user-table-row",
  USER_TABLE_PREVIOUS_BUTTON = "user-table-previous-button",
  USER_TABLE_NEXT_BUTTON = "user-table-next-button",
  ADMIN_SIGN_OUT_BUTTON = "admin-sign-out-button",
  PROFILE_DIALOG = "profile-dialog",
  PROFILE_FIRST_NAME_INPUT = "profile-first-name-input",
  PROFILE_LAST_NAME_INPUT = "profile-last-name-input",
  PROFILE_EMAIL_INPUT = "profile-email-input",
  PROFILE_PHONE_INPUT = "profile-phone-input",
  PROFILE_COMPANY_INPUT = "profile-company-input",
  PROFILE_CANCEL_BUTTON = "profile-cancel-button",
  PROFILE_SAVE_BUTTON = "profile-save-button",
  PROFILE_RESET_BUTTON = "profile-reset-button",
  PROFILE_DELETE_ACCOUNT_BUTTON = "profile-delete-account-button",
  PROFILE_DELETE_CONFIRM_INPUT = "profile-delete-confirm-input",
  PROFILE_DELETE_CONFIRM_BUTTON = "profile-delete-confirm-button",
  SUCCESS_PROFILE_UPDATE = "success-profile-update",
  ERROR_PROFILE_UPDATE = "error-profile-update",
  SUCCESS_PROFILE_RESET = "success-profile-reset",
  ERROR_PROFILE_RESET = "error-profile-reset",
  SUCCESS_ACCOUNT_DELETE = "success-account-delete",
  ERROR_ACCOUNT_DELETE = "error-account-delete",
  SUCCESS_MESSAGE_SEND = "success-message-send",
  ERROR_MESSAGE_SEND = "error-message-send",
  CHAT_INPUT_TEXTAREA = "chat-input-textarea",
  SEND_MESSAGE_BUTTON = "send-message-button",
  CREATE_NEW_CONVERSATION_BUTTON = "create-new-conversation-button",
  CHAT_WINDOW_MESSAGE = "chat-window-message",
  CHAT_WINDOW = "chat-window",
  CHAT_INPUT_FORM = "chat-input-form",
  CHAT_INPUT_CONTAINER = "chat-input-container",
  CHAT_MESSAGES_CONTAINER = "chat-messages-container",
  CHAT_MESSAGE_ITEM = "chat-message-item",
  CHAT_USER_HEADER = "chat-user-header",
  CHAT_EMPTY_STATE = "chat-empty-state",
  CHAT_LOADING_STATE = "chat-loading-state",
  EDIT_CONTRACT_DIALOG = "edit-contract-dialog",
  EDIT_CONTRACT_TITLE_INPUT = "edit-contract-title-input",
  EDIT_CONTRACT_DESCRIPTION_INPUT = "edit-contract-description-input",
  EDIT_CONTRACT_START_DATE_INPUT = "edit-contract-start-date-input",
  EDIT_CONTRACT_TARGET_DATE_INPUT = "edit-contract-target-date-input",
  EDIT_CONTRACT_DUE_DATE_INPUT = "edit-contract-due-date-input",
  EDIT_CONTRACT_APPROVED_SWITCH = "edit-contract-approved-switch",
  EDIT_CONTRACT_SAVE_BUTTON = "edit-contract-save-button",
  EDIT_CONTRACT_CANCEL_BUTTON = "edit-contract-cancel-button",
  EDIT_CONTRACT_PAYMENT_BUTTON = "edit-contract-payment-button",
  EDIT_CONTRACT_ADD_TASK_BUTTON = "edit-contract-add-task-button",
  EDIT_CONTRACT_TASK_ITEM = "edit-contract-task-item",
  EDIT_CONTRACT_TASK_TITLE_INPUT = "edit-contract-task-title-input",
  EDIT_CONTRACT_TASK_DESCRIPTION_INPUT = "edit-contract-task-description-input",
  EDIT_CONTRACT_TASK_PRICE_INPUT = "edit-contract-task-price-input",
  EDIT_CONTRACT_TASK_TOGGLE_PROGRESS_BUTTON = "edit-contract-task-toggle-progress-button",
  EDIT_CONTRACT_TASK_DELETE_BUTTON = "edit-contract-task-delete-button",
  ACTIVE_CONTRACT_DIALOG = "active-contract-dialog",
  ACTIVE_CONTRACT_PROGRESS_STATUS_SELECT = "active-contract-progress-status-select",
  ACTIVE_CONTRACT_REFUND_STATUS_SELECT = "active-contract-refund-status-select",
  ACTIVE_CONTRACT_UPDATE_BUTTON = "active-contract-update-button",
  ACTIVE_CONTRACT_CLOSE_BUTTON = "active-contract-close-button",
  ACTIVE_CONTRACT_TASK_TOGGLE_PROGRESS_BUTTON = "active-contract-task-toggle-progress-button",
  ACTIVE_CONTRACT_PROGRESS_STATUS_BADGE = "active-contract-progress-status-badge",
  ACTIVE_CONTRACT_REFUND_STATUS_BADGE = "active-contract-refund-status-badge",
  ACTIVE_CONTRACT_PAID_STATUS_BADGE = "active-contract-paid-status-badge",
  SUCCESS_CONTRACT_CREATE = "success-contract-create",
  ERROR_CONTRACT_CREATE = "error-contract-create",
  SUCCESS_CONTRACT_UPDATE = "success-contract-update",
  ERROR_CONTRACT_UPDATE = "error-contract-update",
  SUCCESS_CONTRACT_PAYMENT = "success-contract-payment",
  ERROR_CONTRACT_PAYMENT = "error-contract-payment",
  SUCCESS_ACTIVE_CONTRACT_UPDATE = "success-active-contract-update",
  ERROR_ACTIVE_CONTRACT_UPDATE = "error-active-contract-update",
  DELETE_CONTRACTS = "delete-contracts",
  NO_CONTRACTS_YET = "no-contracts-yet",
  SUCCESS_DELETE_CONTRACTS = "success-delete-contracts",
  ERROR_DELETE_CONTRACTS = "error-delete-contracts",
  CONTRACTS_TITLE = "contracts-title",

  // RLS Test page elements
  RLS_TEST_RESULT = "rls-test-result",
  RLS_TEST_PROFILE_SELECT = "rls-test-profile-select",
  RLS_TEST_PROFILE_INSERT = "rls-test-profile-insert",
  RLS_TEST_PROFILE_UPDATE = "rls-test-profile-update",
  RLS_TEST_PROFILE_DELETE = "rls-test-profile-delete",
  RLS_TEST_CONTRACT_SELECT = "rls-test-contract-select",
  RLS_TEST_CONTRACT_INSERT = "rls-test-contract-insert",
  RLS_TEST_CONTRACT_UPDATE = "rls-test-contract-update",
  RLS_TEST_CONTRACT_DELETE = "rls-test-contract-delete",
  RLS_TEST_TASK_SELECT = "rls-test-task-select",
  RLS_TEST_TASK_INSERT = "rls-test-task-insert",
  RLS_TEST_TASK_UPDATE = "rls-test-task-update",
  RLS_TEST_TASK_DELETE = "rls-test-task-delete",
  RLS_TEST_CONVERSATION_SELECT = "rls-test-conversation-select",
  RLS_TEST_CONVERSATION_INSERT = "rls-test-conversation-insert",
  RLS_TEST_CONVERSATION_UPDATE = "rls-test-conversation-update",
  RLS_TEST_CONVERSATION_DELETE = "rls-test-conversation-delete",
  RLS_TEST_MESSAGE_SELECT = "rls-test-message-select",
  RLS_TEST_MESSAGE_INSERT = "rls-test-message-insert",
  RLS_TEST_MESSAGE_UPDATE = "rls-test-message-update",
  RLS_TEST_MESSAGE_DELETE = "rls-test-message-delete",
  RLS_TEST_FILE_UPLOAD_SELECT = "rls-test-file-upload-select",
  RLS_TEST_FILE_UPLOAD_INSERT = "rls-test-file-upload-insert",
  RLS_TEST_FILE_UPLOAD_UPDATE = "rls-test-file-upload-update",
  RLS_TEST_FILE_UPLOAD_DELETE = "rls-test-file-upload-delete",
  RLS_TEST_PAYMENT_SELECT = "rls-test-payment-select",
  RLS_TEST_PAYMENT_INSERT = "rls-test-payment-insert",
  RLS_TEST_PAYMENT_UPDATE = "rls-test-payment-update",
  RLS_TEST_PAYMENT_DELETE = "rls-test-payment-delete",

  // RLS Test behavior badges
  RLS_EXPECTED_FEATURE_BADGE = "rls-expected-feature-badge",
  RLS_UNEXPECTED_BUG_BADGE = "rls-unexpected-bug-badge",

  // RLS Test page buttons and controls
  RLS_EMAIL_INPUT = "rls-email-input",
  RLS_PASSWORD_INPUT = "rls-password-input",
  RLS_SIGN_IN_BUTTON = "rls-sign-in-button",
  RLS_SIGN_IN_ADMIN_BUTTON = "rls-sign-in-admin-button",
  RLS_SIGN_IN_USER_BUTTON = "rls-sign-in-user-button",
  RLS_SIGN_OUT_BUTTON = "rls-sign-out-button",
  RLS_DELETE_ALL_DATA_BUTTON = "rls-delete-all-data-button",
  RLS_SEED_USER_DATA_BUTTON = "rls-seed-user-data-button",
  RLS_SEED_ADMIN_DATA_BUTTON = "rls-seed-admin-data-button",

  // RLS Test action buttons for individual tests
  RLS_TEST_PROFILE_SELECT_BUTTON = "rls-test-profile-select-button",
  RLS_TEST_PROFILE_INSERT_BUTTON = "rls-test-profile-insert-button",
  RLS_TEST_PROFILE_UPDATE_BUTTON = "rls-test-profile-update-button",
  RLS_TEST_PROFILE_DELETE_BUTTON = "rls-test-profile-delete-button",
  RLS_TEST_CONTRACT_SELECT_BUTTON = "rls-test-contract-select-button",
  RLS_TEST_CONTRACT_INSERT_BUTTON = "rls-test-contract-insert-button",
  RLS_TEST_CONTRACT_UPDATE_BUTTON = "rls-test-contract-update-button",
  RLS_TEST_CONTRACT_DELETE_BUTTON = "rls-test-contract-delete-button",
  RLS_TEST_TASK_SELECT_BUTTON = "rls-test-task-select-button",
  RLS_TEST_TASK_INSERT_BUTTON = "rls-test-task-insert-button",
  RLS_TEST_TASK_UPDATE_BUTTON = "rls-test-task-update-button",
  RLS_TEST_TASK_DELETE_BUTTON = "rls-test-task-delete-button",
  RLS_TEST_CONVERSATION_SELECT_BUTTON = "rls-test-conversation-select-button",
  RLS_TEST_CONVERSATION_INSERT_BUTTON = "rls-test-conversation-insert-button",
  RLS_TEST_CONVERSATION_UPDATE_BUTTON = "rls-test-conversation-update-button",
  RLS_TEST_CONVERSATION_DELETE_BUTTON = "rls-test-conversation-delete-button",
  RLS_TEST_MESSAGE_SELECT_BUTTON = "rls-test-message-select-button",
  RLS_TEST_MESSAGE_INSERT_BUTTON = "rls-test-message-insert-button",
  RLS_TEST_MESSAGE_UPDATE_BUTTON = "rls-test-message-update-button",
  RLS_TEST_MESSAGE_DELETE_BUTTON = "rls-test-message-delete-button",
  RLS_TEST_FILE_UPLOAD_SELECT_BUTTON = "rls-test-file-upload-select-button",
  RLS_TEST_FILE_UPLOAD_INSERT_BUTTON = "rls-test-file-upload-insert-button",
  RLS_TEST_FILE_UPLOAD_UPDATE_BUTTON = "rls-test-file-upload-update-button",
  RLS_TEST_FILE_UPLOAD_DELETE_BUTTON = "rls-test-file-upload-delete-button",
  RLS_TEST_PAYMENT_SELECT_BUTTON = "rls-test-payment-select-button",
  RLS_TEST_PAYMENT_INSERT_BUTTON = "rls-test-payment-insert-button",
  RLS_TEST_PAYMENT_UPDATE_BUTTON = "rls-test-payment-update-button",
  RLS_TEST_PAYMENT_DELETE_BUTTON = "rls-test-payment-delete-button",

  // RLS Test toast messages
  RLS_SUCCESS_SIGN_IN_ADMIN = "rls-success-sign-in-admin",
  RLS_ERROR_SIGN_IN_ADMIN = "rls-error-sign-in-admin",
  RLS_SUCCESS_SIGN_IN_USER = "rls-success-sign-in-user",
  RLS_ERROR_SIGN_IN_USER = "rls-error-sign-in-user",
  RLS_SUCCESS_SIGN_OUT = "rls-success-sign-out",
  RLS_ERROR_SIGN_OUT = "rls-error-sign-out",
  RLS_SUCCESS_DELETE_ALL_DATA = "rls-success-delete-all-data",
  RLS_ERROR_DELETE_ALL_DATA = "rls-error-delete-all-data",
  RLS_SUCCESS_SEED_USER_DATA = "rls-success-seed-user-data",
  RLS_ERROR_SEED_USER_DATA = "rls-error-seed-user-data",
  RLS_SUCCESS_SEED_ADMIN_DATA = "rls-success-seed-admin-data",
  RLS_ERROR_SEED_ADMIN_DATA = "rls-error-seed-admin-data",
  RLS_SUCCESS_PROFILE_SELECT = "rls-success-profile-select",
  RLS_ERROR_PROFILE_SELECT = "rls-error-profile-select",
  RLS_SUCCESS_PROFILE_INSERT = "rls-success-profile-insert",
  RLS_ERROR_PROFILE_INSERT = "rls-error-profile-insert",
  RLS_SUCCESS_PROFILE_UPDATE = "rls-success-profile-update",
  RLS_ERROR_PROFILE_UPDATE = "rls-error-profile-update",
  RLS_SUCCESS_PROFILE_DELETE = "rls-success-profile-delete",
  RLS_ERROR_PROFILE_DELETE = "rls-error-profile-delete",
  RLS_SUCCESS_CONTRACT_SELECT = "rls-success-contract-select",
  RLS_ERROR_CONTRACT_SELECT = "rls-error-contract-select",
  RLS_SUCCESS_CONTRACT_INSERT = "rls-success-contract-insert",
  RLS_ERROR_CONTRACT_INSERT = "rls-error-contract-insert",
  RLS_SUCCESS_CONTRACT_UPDATE = "rls-success-contract-update",
  RLS_ERROR_CONTRACT_UPDATE = "rls-error-contract-update",
  RLS_SUCCESS_CONTRACT_DELETE = "rls-success-contract-delete",
  RLS_ERROR_CONTRACT_DELETE = "rls-error-contract-delete",
  RLS_SUCCESS_TASK_SELECT = "rls-success-task-select",
  RLS_ERROR_TASK_SELECT = "rls-error-task-select",
  RLS_SUCCESS_TASK_INSERT = "rls-success-task-insert",
  RLS_ERROR_TASK_INSERT = "rls-error-task-insert",
  RLS_SUCCESS_TASK_UPDATE = "rls-success-task-update",
  RLS_ERROR_TASK_UPDATE = "rls-error-task-update",
  RLS_SUCCESS_TASK_DELETE = "rls-success-task-delete",
  RLS_ERROR_TASK_DELETE = "rls-error-task-delete",
  RLS_SUCCESS_CONVERSATION_SELECT = "rls-success-conversation-select",
  RLS_ERROR_CONVERSATION_SELECT = "rls-error-conversation-select",
  RLS_SUCCESS_CONVERSATION_INSERT = "rls-success-conversation-insert",
  RLS_ERROR_CONVERSATION_INSERT = "rls-error-conversation-insert",
  RLS_SUCCESS_CONVERSATION_UPDATE = "rls-success-conversation-update",
  RLS_ERROR_CONVERSATION_UPDATE = "rls-error-conversation-update",
  RLS_SUCCESS_CONVERSATION_DELETE = "rls-success-conversation-delete",
  RLS_ERROR_CONVERSATION_DELETE = "rls-error-conversation-delete",
  RLS_SUCCESS_MESSAGE_SELECT = "rls-success-message-select",
  RLS_ERROR_MESSAGE_SELECT = "rls-error-message-select",
  RLS_SUCCESS_MESSAGE_INSERT = "rls-success-message-insert",
  RLS_ERROR_MESSAGE_INSERT = "rls-error-message-insert",
  RLS_SUCCESS_MESSAGE_UPDATE = "rls-success-message-update",
  RLS_ERROR_MESSAGE_UPDATE = "rls-error-message-update",
  RLS_SUCCESS_MESSAGE_DELETE = "rls-success-message-delete",
  RLS_ERROR_MESSAGE_DELETE = "rls-error-message-delete",
  RLS_SUCCESS_FILE_UPLOAD_SELECT = "rls-success-file-upload-select",
  RLS_ERROR_FILE_UPLOAD_SELECT = "rls-error-file-upload-select",
  RLS_SUCCESS_FILE_UPLOAD_INSERT = "rls-success-file-upload-insert",
  RLS_ERROR_FILE_UPLOAD_INSERT = "rls-error-file-upload-insert",
  RLS_SUCCESS_FILE_UPLOAD_UPDATE = "rls-success-file-upload-update",
  RLS_ERROR_FILE_UPLOAD_UPDATE = "rls-error-file-upload-update",
  RLS_SUCCESS_FILE_UPLOAD_DELETE = "rls-success-file-upload-delete",
  RLS_ERROR_FILE_UPLOAD_DELETE = "rls-error-file-upload-delete",
  RLS_SUCCESS_PAYMENT_SELECT = "rls-success-payment-select",
  RLS_ERROR_PAYMENT_SELECT = "rls-error-payment-select",
  RLS_SUCCESS_PAYMENT_INSERT = "rls-success-payment-insert",
  RLS_ERROR_PAYMENT_INSERT = "rls-error-payment-insert",
  RLS_SUCCESS_PAYMENT_UPDATE = "rls-success-payment-update",
  RLS_ERROR_PAYMENT_UPDATE = "rls-error-payment-update",
  RLS_SUCCESS_PAYMENT_DELETE = "rls-success-payment-delete",
  RLS_ERROR_PAYMENT_DELETE = "rls-error-payment-delete",

  // RLS Profile Test page elements
  RLS_PROFILE_EMAIL_INPUT = "rls-profile-email-input",
  RLS_PROFILE_PASSWORD_INPUT = "rls-profile-password-input",
  RLS_PROFILE_SIGN_IN_BUTTON = "rls-profile-sign-in-button",
  RLS_PROFILE_SIGN_OUT_BUTTON = "rls-profile-sign-out-button",
  RLS_PROFILE_DELETE_ALL_DATA_BUTTON = "rls-profile-delete-all-data-button",

  // RLS Test Error Dialog
  RLS_ERROR_DIALOG = "rls-error-dialog",
  RLS_ERROR_DIALOG_TITLE = "rls-error-dialog-title",
  RLS_ERROR_DIALOG_CONTENT = "rls-error-dialog-content",
  RLS_ERROR_DIALOG_CLOSE_BUTTON = "rls-error-dialog-close-button",

  // RLS User Action Buttons
  RLS_SELECT_ADMIN_USER_BUTTON = "rls-select-admin-user-button",
  RLS_SELECT_USER_USER_BUTTON = "rls-select-user-user-button",
  RLS_UPDATE_ADMIN_USER_BUTTON = "rls-update-admin-user-button",
  RLS_UPDATE_USER_USER_BUTTON = "rls-update-user-user-button",
  RLS_DELETE_ADMIN_USER_BUTTON = "rls-delete-admin-user-button",
  RLS_DELETE_USER_USER_BUTTON = "rls-delete-user-user-button",
  RLS_INSERT_NEW_USER_BUTTON = "rls-insert-new-user-button",

  // RLS Profile Action Buttons
  RLS_DELETE_ADMIN_PROFILE_BUTTON = "rls-delete-admin-profile-button",
  RLS_DELETE_USER_PROFILE_BUTTON = "rls-delete-user-profile-button",
  RLS_INSERT_ADMIN_PROFILE_BUTTON = "rls-insert-admin-profile-button",
  RLS_INSERT_USER_PROFILE_BUTTON = "rls-insert-user-profile-button",
  RLS_SELECT_ADMIN_PROFILE_BUTTON = "rls-select-admin-profile-button",
  RLS_SELECT_USER_PROFILE_BUTTON = "rls-select-user-profile-button",
  RLS_UPDATE_ADMIN_PROFILE_BUTTON = "rls-update-admin-profile-button",
  RLS_UPDATE_USER_PROFILE_BUTTON = "rls-update-user-profile-button",

  // RLS User Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_USER = "rls-success-select-admin-user",
  RLS_ERROR_SELECT_ADMIN_USER = "rls-error-select-admin-user",
  RLS_SUCCESS_SELECT_USER_USER = "rls-success-select-user-user",
  RLS_ERROR_SELECT_USER_USER = "rls-error-select-user-user",
  RLS_SUCCESS_UPDATE_ADMIN_USER = "rls-success-update-admin-user",
  RLS_ERROR_UPDATE_ADMIN_USER = "rls-error-update-admin-user",
  RLS_SUCCESS_UPDATE_USER_USER = "rls-success-update-user-user",
  RLS_ERROR_UPDATE_USER_USER = "rls-error-update-user-user",
  RLS_SUCCESS_DELETE_ADMIN_USER = "rls-success-delete-admin-user",
  RLS_ERROR_DELETE_ADMIN_USER = "rls-error-delete-admin-user",
  RLS_SUCCESS_DELETE_USER_USER = "rls-success-delete-user-user",
  RLS_ERROR_DELETE_USER_USER = "rls-error-delete-user-user",
  RLS_SUCCESS_INSERT_NEW_USER = "rls-success-insert-new-user",
  RLS_ERROR_INSERT_NEW_USER = "rls-error-insert-new-user",

  // RLS Profile Action Success/Error Toasts
  RLS_SUCCESS_DELETE_ADMIN_PROFILE = "rls-success-delete-admin-profile",
  RLS_ERROR_DELETE_ADMIN_PROFILE = "rls-error-delete-admin-profile",
  RLS_SUCCESS_DELETE_USER_PROFILE = "rls-success-delete-user-profile",
  RLS_ERROR_DELETE_USER_PROFILE = "rls-error-delete-user-profile",
  RLS_SUCCESS_INSERT_ADMIN_PROFILE = "rls-success-insert-admin-profile",
  RLS_ERROR_INSERT_ADMIN_PROFILE = "rls-error-insert-admin-profile",
  RLS_SUCCESS_INSERT_USER_PROFILE = "rls-success-insert-user-profile",
  RLS_ERROR_INSERT_USER_PROFILE = "rls-error-insert-user-profile",
  RLS_SUCCESS_SELECT_ADMIN_PROFILE = "rls-success-select-admin-profile",
  RLS_ERROR_SELECT_ADMIN_PROFILE = "rls-error-select-admin-profile",
  RLS_SUCCESS_SELECT_USER_PROFILE = "rls-success-select-user-profile",
  RLS_ERROR_SELECT_USER_PROFILE = "rls-error-select-user-profile",
  RLS_SUCCESS_UPDATE_ADMIN_PROFILE = "rls-success-update-admin-profile",
  RLS_ERROR_UPDATE_ADMIN_PROFILE = "rls-error-update-admin-profile",
  RLS_SUCCESS_UPDATE_USER_PROFILE = "rls-success-update-user-profile",
  RLS_ERROR_UPDATE_USER_PROFILE = "rls-error-update-user-profile",

  // RLS Contract Action Buttons (Admin specific)
  RLS_SELECT_ADMIN_CONTRACT_BUTTON = "rls-select-admin-contract-button",
  RLS_SELECT_USER_CONTRACT_BUTTON = "rls-select-user-contract-button",
  RLS_INSERT_ADMIN_CONTRACT_BUTTON = "rls-insert-admin-contract-button",
  RLS_INSERT_USER_CONTRACT_BUTTON = "rls-insert-user-contract-button",
  RLS_UPDATE_ADMIN_CONTRACT_BUTTON = "rls-update-admin-contract-button",
  RLS_UPDATE_USER_CONTRACT_BUTTON = "rls-update-user-contract-button",
  RLS_DELETE_ADMIN_CONTRACT_BUTTON = "rls-delete-admin-contract-button",
  RLS_DELETE_USER_CONTRACT_BUTTON = "rls-delete-user-contract-button",
  RLS_DELETE_ALL_USER_CONTRACTS_BUTTON = "rls-delete-all-user-contracts-button",
  RLS_PAY_USER_CONTRACT_BUTTON = "rls-pay-user-contract-button",

  // RLS Contract Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_CONTRACT = "rls-success-select-admin-contract",
  RLS_ERROR_SELECT_ADMIN_CONTRACT = "rls-error-select-admin-contract",
  RLS_SUCCESS_SELECT_USER_CONTRACT = "rls-success-select-user-contract",
  RLS_ERROR_SELECT_USER_CONTRACT = "rls-error-select-user-contract",
  RLS_SUCCESS_INSERT_ADMIN_CONTRACT = "rls-success-insert-admin-contract",
  RLS_ERROR_INSERT_ADMIN_CONTRACT = "rls-error-insert-admin-contract",
  RLS_SUCCESS_INSERT_USER_CONTRACT = "rls-success-insert-user-contract",
  RLS_ERROR_INSERT_USER_CONTRACT = "rls-error-insert-user-contract",
  RLS_SUCCESS_UPDATE_ADMIN_CONTRACT = "rls-success-update-admin-contract",
  RLS_ERROR_UPDATE_ADMIN_CONTRACT = "rls-error-update-admin-contract",
  RLS_SUCCESS_UPDATE_USER_CONTRACT = "rls-success-update-user-contract",
  RLS_ERROR_UPDATE_USER_CONTRACT = "rls-error-update-user-contract",
  RLS_SUCCESS_DELETE_ADMIN_CONTRACT = "rls-success-delete-admin-contract",
  RLS_ERROR_DELETE_ADMIN_CONTRACT = "rls-error-delete-admin-contract",
  RLS_SUCCESS_DELETE_USER_CONTRACT = "rls-success-delete-user-contract",
  RLS_ERROR_DELETE_USER_CONTRACT = "rls-error-delete-user-contract",
  RLS_SUCCESS_DELETE_ALL_USER_CONTRACTS = "rls-success-delete-all-user-contracts",
  RLS_ERROR_DELETE_ALL_USER_CONTRACTS = "rls-error-delete-all-user-contracts",
  RLS_SUCCESS_PAY_USER_CONTRACT = "rls-success-pay-user-contract",
  RLS_ERROR_PAY_USER_CONTRACT = "rls-error-pay-user-contract",

  // RLS Task Action Buttons (Admin/User specific)
  RLS_SELECT_ADMIN_TASK_BUTTON = "rls-select-admin-task-button",
  RLS_SELECT_USER_TASK_BUTTON = "rls-select-user-task-button",
  RLS_INSERT_ADMIN_TASK_BUTTON = "rls-insert-admin-task-button",
  RLS_INSERT_USER_TASK_BUTTON = "rls-insert-user-task-button",
  RLS_UPDATE_ADMIN_TASK_BUTTON = "rls-update-admin-task-button",
  RLS_UPDATE_USER_TASK_BUTTON = "rls-update-user-task-button",
  RLS_DELETE_ADMIN_TASK_BUTTON = "rls-delete-admin-task-button",
  RLS_DELETE_USER_TASK_BUTTON = "rls-delete-user-task-button",
  RLS_DELETE_ALL_USER_TASKS_BUTTON = "rls-delete-all-user-tasks-button",

  // RLS Task Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_TASK = "rls-success-select-admin-task",
  RLS_ERROR_SELECT_ADMIN_TASK = "rls-error-select-admin-task",
  RLS_SUCCESS_SELECT_USER_TASK = "rls-success-select-user-task",
  RLS_ERROR_SELECT_USER_TASK = "rls-error-select-user-task",
  RLS_SUCCESS_INSERT_ADMIN_TASK = "rls-success-insert-admin-task",
  RLS_ERROR_INSERT_ADMIN_TASK = "rls-error-insert-admin-task",
  RLS_SUCCESS_INSERT_USER_TASK = "rls-success-insert-user-task",
  RLS_ERROR_INSERT_USER_TASK = "rls-error-insert-user-task",
  RLS_SUCCESS_UPDATE_ADMIN_TASK = "rls-success-update-admin-task",
  RLS_ERROR_UPDATE_ADMIN_TASK = "rls-error-update-admin-task",
  RLS_SUCCESS_UPDATE_USER_TASK = "rls-success-update-user-task",
  RLS_ERROR_UPDATE_USER_TASK = "rls-error-update-user-task",
  RLS_SUCCESS_DELETE_ADMIN_TASK = "rls-success-delete-admin-task",
  RLS_ERROR_DELETE_ADMIN_TASK = "rls-error-delete-admin-task",
  RLS_SUCCESS_DELETE_USER_TASK = "rls-success-delete-user-task",
  RLS_ERROR_DELETE_USER_TASK = "rls-error-delete-user-task",
  RLS_SUCCESS_DELETE_ALL_USER_TASKS = "rls-success-delete-all-user-tasks",
  RLS_ERROR_DELETE_ALL_USER_TASKS = "rls-error-delete-all-user-tasks",

  // RLS Conversation Action Buttons (Admin/User specific)
  RLS_SELECT_ADMIN_CONVERSATION_BUTTON = "rls-select-admin-conversation-button",
  RLS_SELECT_USER_CONVERSATION_BUTTON = "rls-select-user-conversation-button",
  RLS_INSERT_ADMIN_CONVERSATION_BUTTON = "rls-insert-admin-conversation-button",
  RLS_INSERT_USER_CONVERSATION_BUTTON = "rls-insert-user-conversation-button",
  RLS_UPDATE_ADMIN_CONVERSATION_BUTTON = "rls-update-admin-conversation-button",
  RLS_UPDATE_USER_CONVERSATION_BUTTON = "rls-update-user-conversation-button",
  RLS_DELETE_ADMIN_CONVERSATION_BUTTON = "rls-delete-admin-conversation-button",
  RLS_DELETE_USER_CONVERSATION_BUTTON = "rls-delete-user-conversation-button",
  RLS_DELETE_ALL_USER_CONVERSATIONS_BUTTON = "rls-delete-all-user-conversations-button",

  // RLS Conversation Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_CONVERSATION = "rls-success-select-admin-conversation",
  RLS_ERROR_SELECT_ADMIN_CONVERSATION = "rls-error-select-admin-conversation",
  RLS_SUCCESS_SELECT_USER_CONVERSATION = "rls-success-select-user-conversation",
  RLS_ERROR_SELECT_USER_CONVERSATION = "rls-error-select-user-conversation",
  RLS_SUCCESS_INSERT_ADMIN_CONVERSATION = "rls-success-insert-admin-conversation",
  RLS_ERROR_INSERT_ADMIN_CONVERSATION = "rls-error-insert-admin-conversation",
  RLS_SUCCESS_INSERT_USER_CONVERSATION = "rls-success-insert-user-conversation",
  RLS_ERROR_INSERT_USER_CONVERSATION = "rls-error-insert-user-conversation",
  RLS_SUCCESS_UPDATE_ADMIN_CONVERSATION = "rls-success-update-admin-conversation",
  RLS_ERROR_UPDATE_ADMIN_CONVERSATION = "rls-error-update-admin-conversation",
  RLS_SUCCESS_UPDATE_USER_CONVERSATION = "rls-success-update-user-conversation",
  RLS_ERROR_UPDATE_USER_CONVERSATION = "rls-error-update-user-conversation",
  RLS_SUCCESS_DELETE_ADMIN_CONVERSATION = "rls-success-delete-admin-conversation",
  RLS_ERROR_DELETE_ADMIN_CONVERSATION = "rls-error-delete-admin-conversation",
  RLS_SUCCESS_DELETE_USER_CONVERSATION = "rls-success-delete-user-conversation",
  RLS_ERROR_DELETE_USER_CONVERSATION = "rls-error-delete-user-conversation",
  RLS_SUCCESS_DELETE_ALL_USER_CONVERSATIONS = "rls-success-delete-all-user-conversations",
  RLS_ERROR_DELETE_ALL_USER_CONVERSATIONS = "rls-error-delete-all-user-conversations",

  // RLS Message Action Buttons (Admin/User specific)
  RLS_SELECT_ADMIN_MESSAGE_BUTTON = "rls-select-admin-message-button",
  RLS_SELECT_USER_MESSAGE_BUTTON = "rls-select-user-message-button",
  RLS_INSERT_ADMIN_MESSAGE_BUTTON = "rls-insert-admin-message-button",
  RLS_INSERT_USER_MESSAGE_BUTTON = "rls-insert-user-message-button",
  RLS_UPDATE_ADMIN_MESSAGE_BUTTON = "rls-update-admin-message-button",
  RLS_UPDATE_USER_MESSAGE_BUTTON = "rls-update-user-message-button",
  RLS_DELETE_ADMIN_MESSAGE_BUTTON = "rls-delete-admin-message-button",
  RLS_DELETE_USER_MESSAGE_BUTTON = "rls-delete-user-message-button",
  RLS_DELETE_ALL_USER_MESSAGES_BUTTON = "rls-delete-all-user-messages-button",

  // RLS Message Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_MESSAGE = "rls-success-select-admin-message",
  RLS_ERROR_SELECT_ADMIN_MESSAGE = "rls-error-select-admin-message",
  RLS_SUCCESS_SELECT_USER_MESSAGE = "rls-success-select-user-message",
  RLS_ERROR_SELECT_USER_MESSAGE = "rls-error-select-user-message",
  RLS_SUCCESS_INSERT_ADMIN_MESSAGE = "rls-success-insert-admin-message",
  RLS_ERROR_INSERT_ADMIN_MESSAGE = "rls-error-insert-admin-message",
  RLS_SUCCESS_INSERT_USER_MESSAGE = "rls-success-insert-user-message",
  RLS_ERROR_INSERT_USER_MESSAGE = "rls-error-insert-user-message",
  RLS_SUCCESS_UPDATE_ADMIN_MESSAGE = "rls-success-update-admin-message",
  RLS_ERROR_UPDATE_ADMIN_MESSAGE = "rls-error-update-admin-message",
  RLS_SUCCESS_UPDATE_USER_MESSAGE = "rls-success-update-user-message",
  RLS_ERROR_UPDATE_USER_MESSAGE = "rls-error-update-user-message",
  RLS_SUCCESS_DELETE_ADMIN_MESSAGE = "rls-success-delete-admin-message",
  RLS_ERROR_DELETE_ADMIN_MESSAGE = "rls-error-delete-admin-message",
  RLS_SUCCESS_DELETE_USER_MESSAGE = "rls-success-delete-user-message",
  RLS_ERROR_DELETE_USER_MESSAGE = "rls-error-delete-user-message",
  RLS_SUCCESS_DELETE_ALL_USER_MESSAGES = "rls-success-delete-all-user-messages",
  RLS_ERROR_DELETE_ALL_USER_MESSAGES = "rls-error-delete-all-user-messages",

  // RLS Payment Action Buttons (Admin/User specific)
  RLS_SELECT_ADMIN_PAYMENT_BUTTON = "rls-select-admin-payment-button",
  RLS_SELECT_USER_PAYMENT_BUTTON = "rls-select-user-payment-button",
  RLS_INSERT_ADMIN_PAYMENT_BUTTON = "rls-insert-admin-payment-button",
  RLS_INSERT_USER_PAYMENT_BUTTON = "rls-insert-user-payment-button",
  RLS_UPDATE_ADMIN_PAYMENT_BUTTON = "rls-update-admin-payment-button",
  RLS_UPDATE_USER_PAYMENT_BUTTON = "rls-update-user-payment-button",
  RLS_DELETE_ADMIN_PAYMENT_BUTTON = "rls-delete-admin-payment-button",
  RLS_DELETE_USER_PAYMENT_BUTTON = "rls-delete-user-payment-button",
  RLS_DELETE_ALL_USER_PAYMENTS_BUTTON = "rls-delete-all-user-payments-button",

  // RLS Payment Action Success/Error Toasts
  RLS_SUCCESS_SELECT_ADMIN_PAYMENT = "rls-success-select-admin-payment",
  RLS_ERROR_SELECT_ADMIN_PAYMENT = "rls-error-select-admin-payment",
  RLS_SUCCESS_SELECT_USER_PAYMENT = "rls-success-select-user-payment",
  RLS_ERROR_SELECT_USER_PAYMENT = "rls-error-select-user-payment",
  RLS_SUCCESS_INSERT_ADMIN_PAYMENT = "rls-success-insert-admin-payment",
  RLS_ERROR_INSERT_ADMIN_PAYMENT = "rls-error-insert-admin-payment",
  RLS_SUCCESS_INSERT_USER_PAYMENT = "rls-success-insert-user-payment",
  RLS_ERROR_INSERT_USER_PAYMENT = "rls-error-insert-user-payment",
  RLS_SUCCESS_UPDATE_ADMIN_PAYMENT = "rls-success-update-admin-payment",
  RLS_ERROR_UPDATE_ADMIN_PAYMENT = "rls-error-update-admin-payment",
  RLS_SUCCESS_UPDATE_USER_PAYMENT = "rls-success-update-user-payment",
  RLS_ERROR_UPDATE_USER_PAYMENT = "rls-error-update-user-payment",
  RLS_SUCCESS_DELETE_ADMIN_PAYMENT = "rls-success-delete-admin-payment",
  RLS_ERROR_DELETE_ADMIN_PAYMENT = "rls-error-delete-admin-payment",
  RLS_SUCCESS_DELETE_USER_PAYMENT = "rls-success-delete-user-payment",
  RLS_ERROR_DELETE_USER_PAYMENT = "rls-error-delete-user-payment",
  RLS_SUCCESS_DELETE_ALL_USER_PAYMENTS = "rls-success-delete-all-user-payments",
  RLS_ERROR_DELETE_ALL_USER_PAYMENTS = "rls-error-delete-all-user-payments",
}

export enum RLSButtons {
  // User table operations
  SELECT_OWN_USER_PASS = "select-own-user-pass",
  SELECT_OWN_USER_FAIL = "select-own-user-fail",
  SELECT_OTHER_USER_PASS = "select-other-user-pass", 
  SELECT_OTHER_USER_FAIL = "select-other-user-fail",
  INSERT_USER_PASS = "insert-user-pass",
  INSERT_USER_FAIL = "insert-user-fail",
  UPDATE_OWN_USER_PASS = "update-own-user-pass",
  UPDATE_OWN_USER_FAIL = "update-own-user-fail",
  UPDATE_OTHER_USER_PASS = "update-other-user-pass",
  UPDATE_OTHER_USER_FAIL = "update-other-user-fail",
  DELETE_OWN_USER_PASS = "delete-own-user-pass",
  DELETE_OWN_USER_FAIL = "delete-own-user-fail",
  DELETE_OTHER_USER_PASS = "delete-other-user-pass",
  DELETE_OTHER_USER_FAIL = "delete-other-user-fail",

  // Session table operations
  SELECT_OWN_SESSION_PASS = "select-own-session-pass",
  SELECT_OWN_SESSION_FAIL = "select-own-session-fail",
  SELECT_OTHER_SESSION_PASS = "select-other-session-pass",
  SELECT_OTHER_SESSION_FAIL = "select-other-session-fail",
  INSERT_OWN_SESSION_PASS = "insert-own-session-pass",
  INSERT_OWN_SESSION_FAIL = "insert-own-session-fail",
  INSERT_OTHER_SESSION_PASS = "insert-other-session-pass",
  INSERT_OTHER_SESSION_FAIL = "insert-other-session-fail",
  UPDATE_OWN_SESSION_PASS = "update-own-session-pass",
  UPDATE_OWN_SESSION_FAIL = "update-own-session-fail",
  UPDATE_OTHER_SESSION_PASS = "update-other-session-pass",
  UPDATE_OTHER_SESSION_FAIL = "update-other-session-fail",
  DELETE_OWN_SESSION_PASS = "delete-own-session-pass",
  DELETE_OWN_SESSION_FAIL = "delete-own-session-fail",
  DELETE_OTHER_SESSION_PASS = "delete-other-session-pass",
  DELETE_OTHER_SESSION_FAIL = "delete-other-session-fail",

  // Account table operations  
  SELECT_OWN_ACCOUNT_PASS = "select-own-account-pass",
  SELECT_OWN_ACCOUNT_FAIL = "select-own-account-fail",
  SELECT_OTHER_ACCOUNT_PASS = "select-other-account-pass",
  SELECT_OTHER_ACCOUNT_FAIL = "select-other-account-fail",
  INSERT_OWN_ACCOUNT_PASS = "insert-own-account-pass",
  INSERT_OWN_ACCOUNT_FAIL = "insert-own-account-fail",
  INSERT_OTHER_ACCOUNT_PASS = "insert-other-account-pass",
  INSERT_OTHER_ACCOUNT_FAIL = "insert-other-account-fail",
  UPDATE_OWN_ACCOUNT_PASS = "update-own-account-pass",
  UPDATE_OWN_ACCOUNT_FAIL = "update-own-account-fail",
  UPDATE_OTHER_ACCOUNT_PASS = "update-other-account-pass",
  UPDATE_OTHER_ACCOUNT_FAIL = "update-other-account-fail",
  DELETE_OWN_ACCOUNT_PASS = "delete-own-account-pass",
  DELETE_OWN_ACCOUNT_FAIL = "delete-own-account-fail",
  DELETE_OTHER_ACCOUNT_PASS = "delete-other-account-pass",
  DELETE_OTHER_ACCOUNT_FAIL = "delete-other-account-fail",

  // Verification table operations (admin only)
  SELECT_VERIFICATION_PASS = "select-verification-pass",
  SELECT_VERIFICATION_FAIL = "select-verification-fail",
  INSERT_VERIFICATION_PASS = "insert-verification-pass",
  INSERT_VERIFICATION_FAIL = "insert-verification-fail",
  UPDATE_VERIFICATION_PASS = "update-verification-pass",
  UPDATE_VERIFICATION_FAIL = "update-verification-fail",
  DELETE_VERIFICATION_PASS = "delete-verification-pass",
  DELETE_VERIFICATION_FAIL = "delete-verification-fail",

  // Profile table operations
  SELECT_OWN_PROFILE_PASS = "select-own-profile-pass",
  SELECT_OWN_PROFILE_FAIL = "select-own-profile-fail",
  SELECT_OTHER_PROFILE_PASS = "select-other-profile-pass",
  SELECT_OTHER_PROFILE_FAIL = "select-other-profile-fail",
  INSERT_OWN_PROFILE_PASS = "insert-own-profile-pass",
  INSERT_OWN_PROFILE_FAIL = "insert-own-profile-fail",
  INSERT_OTHER_PROFILE_PASS = "insert-other-profile-pass",
  INSERT_OTHER_PROFILE_FAIL = "insert-other-profile-fail",
  UPDATE_OWN_PROFILE_PASS = "update-own-profile-pass",
  UPDATE_OWN_PROFILE_FAIL = "update-own-profile-fail",
  UPDATE_OTHER_PROFILE_PASS = "update-other-profile-pass",
  UPDATE_OTHER_PROFILE_FAIL = "update-other-profile-fail",
  DELETE_OWN_PROFILE_PASS = "delete-own-profile-pass",
  DELETE_OWN_PROFILE_FAIL = "delete-own-profile-fail",
  DELETE_OTHER_PROFILE_PASS = "delete-other-profile-pass",
  DELETE_OTHER_PROFILE_FAIL = "delete-other-profile-fail",

  // Contract table operations
  SELECT_OWN_CONTRACT_PASS = "select-own-contract-pass",
  SELECT_OWN_CONTRACT_FAIL = "select-own-contract-fail",
  SELECT_OTHER_CONTRACT_PASS = "select-other-contract-pass",
  SELECT_OTHER_CONTRACT_FAIL = "select-other-contract-fail",
  INSERT_OWN_CONTRACT_PASS = "insert-own-contract-pass",
  INSERT_OWN_CONTRACT_FAIL = "insert-own-contract-fail",
  INSERT_OTHER_CONTRACT_PASS = "insert-other-contract-pass",
  INSERT_OTHER_CONTRACT_FAIL = "insert-other-contract-fail",
  UPDATE_OWN_UNPAID_CONTRACT_PASS = "update-own-unpaid-contract-pass",
  UPDATE_OWN_UNPAID_CONTRACT_FAIL = "update-own-unpaid-contract-fail",
  UPDATE_OWN_PAID_CONTRACT_PASS = "update-own-paid-contract-pass",
  UPDATE_OWN_PAID_CONTRACT_FAIL = "update-own-paid-contract-fail",
  UPDATE_OTHER_CONTRACT_PASS = "update-other-contract-pass",
  UPDATE_OTHER_CONTRACT_FAIL = "update-other-contract-fail",
  DELETE_OWN_CONTRACT_PASS = "delete-own-contract-pass",
  DELETE_OWN_CONTRACT_FAIL = "delete-own-contract-fail",
  DELETE_OTHER_CONTRACT_PASS = "delete-other-contract-pass",
  DELETE_OTHER_CONTRACT_FAIL = "delete-other-contract-fail",

  // Task table operations
  SELECT_OWN_TASK_PASS = "select-own-task-pass",
  SELECT_OWN_TASK_FAIL = "select-own-task-fail",
  SELECT_OTHER_TASK_PASS = "select-other-task-pass",
  SELECT_OTHER_TASK_FAIL = "select-other-task-fail",
  INSERT_OWN_TASK_PASS = "insert-own-task-pass", 
  INSERT_OWN_TASK_FAIL = "insert-own-task-fail",
  INSERT_OTHER_TASK_PASS = "insert-other-task-pass",
  INSERT_OTHER_TASK_FAIL = "insert-other-task-fail",
  UPDATE_OWN_TASK_PASS = "update-own-task-pass",
  UPDATE_OWN_TASK_FAIL = "update-own-task-fail",
  UPDATE_OTHER_TASK_PASS = "update-other-task-pass",
  UPDATE_OTHER_TASK_FAIL = "update-other-task-fail",
  DELETE_OWN_TASK_PASS = "delete-own-task-pass",
  DELETE_OWN_TASK_FAIL = "delete-own-task-fail",
  DELETE_OTHER_TASK_PASS = "delete-other-task-pass",
  DELETE_OTHER_TASK_FAIL = "delete-other-task-fail",

  // Conversation table operations
  SELECT_OWN_CONVERSATION_PASS = "select-own-conversation-pass",
  SELECT_OWN_CONVERSATION_FAIL = "select-own-conversation-fail",
  SELECT_OTHER_CONVERSATION_PASS = "select-other-conversation-pass",
  SELECT_OTHER_CONVERSATION_FAIL = "select-other-conversation-fail",
  INSERT_CONVERSATION_PASS = "insert-conversation-pass",
  INSERT_CONVERSATION_FAIL = "insert-conversation-fail",
  UPDATE_OWN_CONVERSATION_PASS = "update-own-conversation-pass",
  UPDATE_OWN_CONVERSATION_FAIL = "update-own-conversation-fail",
  UPDATE_OTHER_CONVERSATION_PASS = "update-other-conversation-pass",
  UPDATE_OTHER_CONVERSATION_FAIL = "update-other-conversation-fail",
  DELETE_OWN_CONVERSATION_PASS = "delete-own-conversation-pass",
  DELETE_OWN_CONVERSATION_FAIL = "delete-own-conversation-fail",
  DELETE_OTHER_CONVERSATION_PASS = "delete-other-conversation-pass",
  DELETE_OTHER_CONVERSATION_FAIL = "delete-other-conversation-fail",

  // Message table operations
  SELECT_OWN_MESSAGE_PASS = "select-own-message-pass",
  SELECT_OWN_MESSAGE_FAIL = "select-own-message-fail",
  SELECT_OTHER_MESSAGE_PASS = "select-other-message-pass",
  SELECT_OTHER_MESSAGE_FAIL = "select-other-message-fail",
  INSERT_OWN_MESSAGE_PASS = "insert-own-message-pass",
  INSERT_OWN_MESSAGE_FAIL = "insert-own-message-fail",
  INSERT_OTHER_MESSAGE_PASS = "insert-other-message-pass",
  INSERT_OTHER_MESSAGE_FAIL = "insert-other-message-fail",
  UPDATE_OWN_MESSAGE_PASS = "update-own-message-pass",
  UPDATE_OWN_MESSAGE_FAIL = "update-own-message-fail",
  UPDATE_OTHER_MESSAGE_PASS = "update-other-message-pass",
  UPDATE_OTHER_MESSAGE_FAIL = "update-other-message-fail",
  DELETE_OWN_MESSAGE_PASS = "delete-own-message-pass",
  DELETE_OWN_MESSAGE_FAIL = "delete-own-message-fail",
  DELETE_OTHER_MESSAGE_PASS = "delete-other-message-pass",
  DELETE_OTHER_MESSAGE_FAIL = "delete-other-message-fail",

  // File upload table operations
  SELECT_OWN_FILE_UPLOAD_PASS = "select-own-file-upload-pass",
  SELECT_OWN_FILE_UPLOAD_FAIL = "select-own-file-upload-fail",
  SELECT_OTHER_FILE_UPLOAD_PASS = "select-other-file-upload-pass",
  SELECT_OTHER_FILE_UPLOAD_FAIL = "select-other-file-upload-fail",
  INSERT_OWN_FILE_UPLOAD_PASS = "insert-own-file-upload-pass",
  INSERT_OWN_FILE_UPLOAD_FAIL = "insert-own-file-upload-fail",
  INSERT_OTHER_FILE_UPLOAD_PASS = "insert-other-file-upload-pass",
  INSERT_OTHER_FILE_UPLOAD_FAIL = "insert-other-file-upload-fail",
  UPDATE_OWN_FILE_UPLOAD_PASS = "update-own-file-upload-pass",
  UPDATE_OWN_FILE_UPLOAD_FAIL = "update-own-file-upload-fail",
  UPDATE_OTHER_FILE_UPLOAD_PASS = "update-other-file-upload-pass",
  UPDATE_OTHER_FILE_UPLOAD_FAIL = "update-other-file-upload-fail",
  DELETE_OWN_FILE_UPLOAD_PASS = "delete-own-file-upload-pass",
  DELETE_OWN_FILE_UPLOAD_FAIL = "delete-own-file-upload-fail",
  DELETE_OTHER_FILE_UPLOAD_PASS = "delete-other-file-upload-pass",
  DELETE_OTHER_FILE_UPLOAD_FAIL = "delete-other-file-upload-fail",

  // Payment table operations
  SELECT_OWN_PAYMENT_PASS = "select-own-payment-pass",
  SELECT_OWN_PAYMENT_FAIL = "select-own-payment-fail",
  SELECT_OTHER_PAYMENT_PASS = "select-other-payment-pass",
  SELECT_OTHER_PAYMENT_FAIL = "select-other-payment-fail",
  INSERT_OWN_PAYMENT_PASS = "insert-own-payment-pass",
  INSERT_OWN_PAYMENT_FAIL = "insert-own-payment-fail",
  INSERT_OTHER_PAYMENT_PASS = "insert-other-payment-pass",
  INSERT_OTHER_PAYMENT_FAIL = "insert-other-payment-fail",
  UPDATE_OWN_PAYMENT_PASS = "update-own-payment-pass",
  UPDATE_OWN_PAYMENT_FAIL = "update-own-payment-fail",
  UPDATE_OTHER_PAYMENT_PASS = "update-other-payment-pass",
  UPDATE_OTHER_PAYMENT_FAIL = "update-other-payment-fail",
  DELETE_OWN_PAYMENT_PASS = "delete-own-payment-pass",
  DELETE_OWN_PAYMENT_FAIL = "delete-own-payment-fail",
  DELETE_OTHER_PAYMENT_PASS = "delete-other-payment-pass",
  DELETE_OTHER_PAYMENT_FAIL = "delete-other-payment-fail",

  // Authentication and setup operations
  SIGN_IN_ADMIN_PASS = "sign-in-admin-pass",
  SIGN_IN_ADMIN_FAIL = "sign-in-admin-fail",
  SIGN_IN_USER_PASS = "sign-in-user-pass",
  SIGN_IN_USER_FAIL = "sign-in-user-fail",
  SIGN_OUT_PASS = "sign-out-pass",
  SIGN_OUT_FAIL = "sign-out-fail",
  DELETE_ALL_DATA_PASS = "delete-all-data-pass",
  DELETE_ALL_DATA_FAIL = "delete-all-data-fail",
}
