//-| File path: types/cypress.types.ts
export enum CyDataAttributes {
  SUCCESS_AUTH_SIGN_IN = "success-auth-sign-in",
  ERROR_AUTH_SIGN_IN = "error-auth-sign-in",
  SUCCESS_AUTH_SIGN_UP = "success-auth-sign-up",
  ERROR_AUTH_SIGN_UP = "error-auth-sign-up",
  AUTH_DIALOG = "auth-dialog",
  AUTH_EMAIL_INPUT = "auth-email-input",
  AUTH_PASSWORD_INPUT = "auth-password-input",
  AUTH_SUBMIT_BUTTON = "auth-submit-button",
  AUTH_TOGGLE_MODE_BUTTON = "auth-toggle-mode-button",
  SIGN_IN_BUTTON = "sign-in-button",
  PROFILE_BUTTON = "profile-button",
  SIGN_OUT_BUTTON = "sign-out-button",
  SUCCESS_SIGN_OUT = "success-sign-out",
  ERROR_SIGN_OUT = "error-sign-out",
  SUCCESS_RESEND_EMAIL = "success-resend-email",
  ERROR_RESEND_EMAIL = "error-resend-email",
  TOGGLE_SIDEBAR_BUTTON = "toggle-sidebar-button",
  RESEND_EMAIL_BUTTON = "resend-email-button",
  SIGN_OUT_VERIFY_BUTTON = "sign-out-verify-button",
  CONVERSATION_ITEM = "conversation-item",
  UNREAD_BADGE = "unread-badge",
  CREATE_CONTRACT_BUTTON = "create-contract-button",
  CONTRACT_ITEM = "contract-item",
  CONTRACT_UNAPPROVED_BADGE = "contract-unapproved-badge",
  PROFILE_MENU_BUTTON = "profile-menu-button",
  PROFILE_BUTTON_COLLAPSED = "profile-button-collapsed",
  SIGN_OUT_BUTTON_COLLAPSED = "sign-out-button-collapsed",
}
